services:
  sidorov-web:
    image: ghcr.io/toptuk/sidorov_ru:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: s-sidorov-site
    restart: always
    volumes:
      - ./certs:/etc/ssl
      - ./nginx.production.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=s-sidorov.ru,www.s-sidorov.ru
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
    networks:
      - pmi_network

networks:
  pmi_network:
    external: true
